### PR TITLE
Sep 2019 cleanup

### PR DESCRIPTION
**Pull request by ifenty**
1) removed routines that read netcdf files in the format where each variable was split into different tiles.  We are not going to adopt that format.  Too many files and i/o overhead.

2) retired tile_exchange and tile_rotation to the new incomplete directory since these libraries do not work and are not being actively developed

3)  added the small OSNAP netcdf files from stampede2 to the /bin directory

4) updated version number for pypi and development level.   Now:
Development Status :: 5 - Production/Stable   

5) made very small change to calc_meridional_transports because the maskC, maskW, and maskS are no longer coordinates saved in the NetCDF grid file.  Now if you want them you make them from the hFacs and then you can add them to your dataset object.  Tim's calc_meridional routines need these masks but assumes they are part of the coordinate variables.  My change allows the mask fields to be 'variables' in the dataset, not just 'coordinates'.

### CODE REVIEW

**Comment by timothyas** [comment]
Don't like the directory name `bin/`? ;) Any reason for this change? It breaks `test/test_llc_array_conversion.py` and `get_basins.py`

**Comment by ifenty** [comment]
@timothyas Thanks for the comments.  I removed OSNAP, changed rhoconst in both places, kept heat capacity as 4000 (apparently that's actually fine).   I don't know how to see the changes you requested.

**Comment by ifenty** [comment]
I like 'bin' except I found that if we download the repository from pypi using 'pip' then the binary files (non *.py files) in the '/bin' aren't downloaded or included in the local install directory.  I dug around and found a solution which does download these binary files but they don't go to the /bin directory in the ecco-v4-py library folder but actually in a directory relative to the user's home directory.  The reason I changed 'bin' was that /home/username/bin  tends to have executable binaries (/home/username/bin) and I thought it would be weird to include our binary files there.

Do you know how to get those binary files to be installed when we use pip?  If not, maybe the right way forward is to instruct users to download those files from the github or some other directory.  What do you think?

**Comment by timothyas** [comment]
Hey thanks @ifenty, I see this is a bit more complicated with the `bin/` directory... After reading up on [some python packaging documentation](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/introduction.html#) it seems like `bin/` is just not the name we want to use after all, because it is reserved for executables that the package needs. If we rename the directory to `binary_data/` this shouldn't happen right? Perhaps we can go ahead with that (after making changes to `get_basins.py` and the tests), and see if binary data then gets installed as we want it to. 

Another option we could explore is to host the data at a different location, like [figshare](https://figshare.com/). This is where xmitgcm hosts their test data, for example. The upside to this is that the ecco_v4_py package would be lighter and install faster (right now it's a bit slow since we/I added the hFac and state_3d files for testing), and we could add more data files for testing without worrying about overdoing it on space. The downside would be specifically for `get_basin`, which requires a single 2D field to operate. It would be nice for this file to simply come with ecco_v4_py, no matter how the user gets it. However, maybe it would be possible to write this module in a way that it looks for the basins.data file and if it doesn't find it, prompts the user to download and/or downloads the file itself (like cartopy does for features the first time you want to add a feature) from something like figshare. 

What do you think about trying the switch to `binary_data/` and see if that comes with a `pip install`, then we could explore the external file storage options for the future?

**Pull request merged**
