### PR TITLE
Cleanup september 2019

### PR DESCRIPTION
**Pull request by ifenty**
Made basin directory an argumen to get_basin_mask

Added link to figshare collection that now has binary files needed for some of the ecco-v4-py subroutines.
     https://figshare.com/articles/Binary_files_for_the_ecco-v4-py_Python_package_/9932162

Added some error message if the grid file is not found.

### CODE REVIEW

**Comment by ifenty** [comment]
@timothyas Apologies if there is any confusion on github.  I tried updating the branch but ran into some hiccups.  Check out the revisions which includes a link to where the binary files are hosted on figshare.

**Comment by ifenty** [comment]
@timothyas we can iterate further about how to handle the binary files.  I just want to have these changes committed for the time being

**Comment by timothyas** [comment]
Hey thanks @ifenty! Yeah I agree, best to get this implemented and then we can always iterate on the best solution.

**Comment by timothyas** [comment]
PS you mentioned having some hiccups with the branch, and I think that's because this PR is made with the same branch as #70. Just fyi for the future, I think it would be cleaner to re checkout master, pull or rebase from upstream/master to your origin/master branch, then checkout a new branch on top of that for the new PR. It seems like nothing is out of place and it all ended up ok though. Thanks again!

**Pull request merged**
