### PR TITLE
Update netcdf generation routines

### PR DESCRIPTION
**Pull request by ifenty**
most of the individual line-by-line changes are removal of trailing whitespace.  

A few changes in read_bin_llc.

1. Adding metadata is updated.  it's set up to use the new metadata created for the release of ECCO to PODAAC.

2. I turned off 'ignore unknown variables' because the xmitgcm load routine will silently skip loading a variable that isn't in available_diagnostics.log. Having an updated and consistent available_diagnostics.log has to be a requirement for using this routine because available_diagnostics.log tells xmitgcm whether the variable is a 'c', 'u', or 'v' variable, whether it's 2D or 3D etc.

3. Grid variables are not longer blindly promoted to be coordinates because that is not CF compliant.  Only actual coordinates are now promoted to be coordinates.

### CODE REVIEW

**Comment by ifenty** [comment]
I've 'resolved conflicts' three times already, apparently it doesn't save those changes anywhere.

**Comment by ifenty** [comment]
@timothyas what are the codecov tests?

**Comment by timothyas** [comment]
Hey @ifenty - this is strange, I’m not sure where the conflicts are coming from. I’ll check this out on Monday. 

The codecov tests check to see if the percentage of code that is covered by tests drops with the addition of the code in the PR. Right now it’s a little aggressive, any drop causes the checks to show “fail” but we could have a threshold, say 5%, so that the checks pass unless coverage drops 5%. What do you think?

**Comment by ifenty** [comment]
> Hey @ifenty - this is strange, I’m not sure where the conflicts are coming from. I’ll check this out on Monday. 
> 
> The codecov tests check to see if the percentage of code that is covered by tests drops with the addition of the code in the PR. Right now it’s a little aggressive, any drop causes the checks to show “fail” but we could have a threshold, say 5%, so that the checks pass unless coverage drops 5%. What do you think?


I think the 5% is ok, but I think the drop was mainly because new code was added that isn't tested. Anyway the first set of Travis fails were because I changed the default behavior to have grid parameters like drF no longer considered coordinates because that violates CF convention.  I think your tests assume that they were coordinates and so the tests failed.  I changed the default behavior back to having them loaded as coordinates and then the travis tests passed.

**Comment by timothyas** [comment]
Hey @ifenty 
>I think your tests assume that they were coordinates and so the tests failed. I changed the default behavior back to having them loaded as coordinates and then the travis tests passed.

Yeah that's correct. In the tests I create a dataset using the `load_ecco_vars_from_mds` function, and rely on having the `drF` variables as coordinates to do some very simple tests. I guess this could be changed, but is keeping them as coordinates a big deal? Even if it is not strictly CF compliant, it seems to make intuitive sense to me at least... 

Otherwise it all seems to be good.

**Comment by timothyas** [comment]
PS would you be able to release the newest version to pip whenever you get the chance?

**Comment by ifenty** [comment]
@timothyas I used to think that the grid fields like drF were fine as xarray 'coordinates' but looking into it more deeply, those many of those fields aren't coordiantes at all in the sense that they aren't alternative labels for the different dimension (the distinction between dimensions like i,j,k and geographical coordinate like XC, YC, Z).  Just because the grid  parameters  'don't change' doesn't mean that they are coordiantes. (Actually, funny sidebar hFac* do change in ECCO V4 we just don't output it.).

If you poke your head into the rabbit hole of the xarray github issue discussion you'll see that the issue seems to have come up before. The xarray website is actually good at demonstrating coordinates (coordinates named 'space' when dimensions are i and j).  I think my  confusion on the topic came from the first xmitgcm examples I first saw that loaded grid parameters as coordinates.  Some are (XC, XG, YC, YG, Z, Z_u, Z_l, Z_p1), all of those are definitely coordinates, and some aren't. I guess the xmitgcm authors weren't feeling picky and since there are no computational consequences with having a variable be a nondimensional coordinate or data variable, they just lumped all of the grid variables as coordinates.

Also, I found this [xarray 'terminology'](https://github.com/pydata/xarray/blob/d9ebcafaddf0bb80052d30f43ca5ea18a5c7229f/doc/terminology.rst) page useful.  Maybe I'm reading with a bias but I think it is supportive.  

```
Coordinate
        An array that labels a dimension or set of dimensions of another
        ``DataArray``. In the usual one-dimensional case, the coordinate array's
        values can loosely be thought of as tick labels along a dimension. There
        are two types of coordinate arrays: *dimension coordinates* and
        *non-dimension coordinates* (see below). A coordinate named ``x`` can be
        retrieved from ``arr.coords[x]``. A ``DataArray`` can have more
        coordinates than dimensions because a single dimension can be labeled by
        multiple coordinate arrays. However, only one coordinate array can be a
        assigned as a particular dimension's dimension coordinate array. As a
        consequence, ``len(arr.dims) <= len(arr.coords)`` in general.

    Dimension coordinate
        A one-dimensional coordinate array assigned to ``arr`` with both a name
        and dimension name in ``arr.dims``. Dimension coordinates are used for
        label-based indexing and alignment, like the index found on a
        :py:class:`pandas.DataFrame` or :py:class:`pandas.Series`. In fact,
        dimension coordinates use :py:class:`pandas.Index` objects under the
        hood for efficient computation. Dimension coordinates are marked by
        ``*`` when printing a ``DataArray`` or ``Dataset``.

    Non-dimension coordinate
        A coordinate array assigned to ``arr`` with a name in ``arr.coords`` but
        *not* in ``arr.dims``. These coordinates arrays can be one-dimensional
        or multidimensional, and they are useful for auxiliary labeling. As an
        example, multidimensional coordinates are often used in geoscience
        datasets when :doc:`the data's physical coordinates (such as latitude
        and longitude) differ from their logical coordinates
        <examples/multidimensional-coords>`. However, non-dimension coordinates
        are not indexed, and any operation on non-dimension coordinates that
        leverages indexing will fail. Printing ``arr.coords`` will print all of
        ``arr``'s coordinate names, with the corresponding dimension(s) in
        parentheses. For example, ``coord_name (dim_name) 1 2 3 ...``.

```

Anyway, based on the above the next version of ECCO output will have the grid measures as data variables and reserve coordinates for geographical labels XC, XG, YC, YG, Z, Z_u, Z_l, Z_p1 (i.e., the 'tick-marks' that label a dimension).  Therefore, I'd have tests check for grid measures in *both* coords and data_vars for backwards compatability.

**Comment by timothyas** [comment]
Nice, thanks @ifenty for the super thorough reply. Wow that is quite a rabbit hole, I'm not sure I want to go down it at the moment! ;) 

The good thing is that this only matters for the tests, the actual use of the functions does not rely on anything being labelled a coordinate or not, for example `calc_meridional_vol_trsp` just grabs e.g. `drF`, `dxG`, `dyG`, etc...

In the tests, though, I create a "fake" dataset to pass to the functions. In creating that test dataset I call `coords = ds.coords.to_dataset()`, thinking that the volume elements `drF` etc... will be there. So the tests were failing simply because they weren't getting set up properly. But this is so not essential, and I can change that if you like.

**Pull request merged**
