### PR TITLE
Add projection features

### PR DESCRIPTION
**Pull request by emmomp**
Alterations to tile_plot_proj
- Added the 'LambertConformal' cartopy projection
- Added optional user inputs user_lat_0 and parallels
- Lat_lim is used as the 'cutoff' input for the LambertConformal projection
- Changed default colormap to viridis (see https://agilescientific.com/blog/2017/12/14/no-more-rainbows or #endrainbow on twitter)
- Greatly simplified _create_projection_axis. Improvements mean it should now be much simpler to add extra projections and any of user_lon_0, user_lat_0, lat_lim, parallels that are defined are passed to the projection definition.

Alteration to resample_to_latlon ensures the num input passed to np.linspace is an int, as required for numpy v1.18+

Tested on the plotting tutorial and it all works as expected.

### CODE REVIEW

**Comment by timothyas** [comment]
Once again, thank you @emmomp! This is awesome. 
- `_create_projection_axis` is much cleaner: my original version was pre-learning-python and this is much more elegant
- other changes are straight forward version fixing (int stuff) and feature additions (lambert conformal, user_lat0)
- Big kudos for "fixing" the rainbow default :) I'm wondering if you would agree with taking this one step further to, just like xarray does, infer whether the default should be sequential or divergent? We already compute "cmin/cmax" so this would not be difficult. I can add these changes (I think, since I'm an admin?) later today.

**Comment by emmomp** [comment]
I agree it would be nice to have the red&blue cmap automatically selected for divergent data as in xarray. I realised after I submitted the pull request that the cmap defaults in tile_plot.py should also be updated accordingly for consistency - I'll leave that to you if you are going to tinker with it anyways?

**Comment by timothyas** [comment]
Hey @emmomp, I went ahead and added the diverging cmap default. Also noticed that the EqualEarth projection may cause errors (as it did for me), so added some protection there. Let me know if you can think of anything else that would be appropriate for the PR, otherwise I'll merge ASAP. 

Thanks!

**Comment by emmomp** [comment]
Looks good to me @timothyas

**Pull request merged**
